IF DB_ID('FeiraApp') IS NULL
BEGIN
CREATE DATABASE [FeiraApp];
END
GO

USE [FeiraApp]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'DEINFO_AB_FEIRASLIVRES_2014'))
BEGIN
DROP TABLE [dbo].[DEINFO_AB_FEIRASLIVRES_2014]
END

  CREATE TABLE [dbo].[DEINFO_AB_FEIRASLIVRES_2014](	
	[ID] [INT] NOT NULL,
	[LAT] [bigint] NOT NULL,
	[LONG] [bigint] NOT NULL,
	[SETCENS] [varchar](32) NOT NULL,
	[AREAP] [varchar](32) NOT NULL,
	[CODDIST] [int] NOT NULL,
	[DISTRITO] [varchar](128) NOT NULL,
	[CODSUBPREF] [int] NOT NULL,
	[SUBPREFE] [varchar](128) NOT NULL,
	[REGIAO5] [varchar](128) NOT NULL,
	[REGIAO8] [varchar](128) NOT NULL,
	[NOME_FEIRA] [varchar](128) NOT NULL,
	[REGISTRO] [varchar](32) NOT NULL,
	[LOGRADOURO] [varchar](256) NOT NULL,
	[NUMERO] [varchar](32) NULL,
	[BAIRRO] [varchar](128) NOT NULL,
	[REFERENCIA] [varchar](128) NULL)

BULK INSERT [dbo].[DEINFO_AB_FEIRASLIVRES_2014]
FROM 'C:\Projetos\Felipe\api-feira\fair.api\Datasource\DEINFO_AB_FEIRASLIVRES_2014.csv'
WITH
(
FIRSTROW = 2,
LASTROW = 880,
FIELDTERMINATOR = ',',
ROWTERMINATOR = '0x0A'
) 
GO

ALTER TABLE [dbo].[DEINFO_AB_FEIRASLIVRES_2014] DROP COLUMN ID
GO

ALTER TABLE [dbo].[DEINFO_AB_FEIRASLIVRES_2014] ADD ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
GO





